### ISSUE TITLE
Doesn't work with the latest Google Music update

### ISSUE THREAD

**Issue by leTel** [ojcarcete/googleplay-lyrics#5]
Google music was updated recently and unfortunately, your great extension doesn't work anymore.
I don't know where to find the change log for the google music update, so I can't really be specific on the issue, sorry for that. I heard the DOM was reworked but can't confirm this info.

**Comment by ojcarcete** [comment]
Just released a new version with a quick fix (v1.0.14), although I might make changes soon, because Google Music's layout has changed quite a bit and I am not too happy with the integration within the UI now.

As always, I am open to suggestions.

Thank you for reporting the issue!
