### ISSUE TITLE
Allow to change font color (dark/light)

### ISSUE THREAD

**Issue by leTel** [ojcarcete/googleplay-lyrics#6]
An improvement suggestion :
Can you allow the user to choose font color (a really simple black or white would do the trick).

There is a lot of extension for google music and some of them changes the background color.

For example, I use  [Play Midnight]( https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci) which set a black background color, so I have to choose between this great extension and yours (which is even greater :P ).

EDIT:
For the specific use of Lyrics with Play Midnight, I did found a strange workaround. If you open the queue <img width="28" alt="screen shot 2016-09-16 at 09 52 12" src="https://cloud.githubusercontent.com/assets/6904963/18579021/4510f0ee-7bf3-11e6-95ec-553dc5128cca.png"> then close it, the lyrics font color change from black to white.

**Comment by ojcarcete** [comment]
I will play with it and see what I can do next week.

Ideally it should be automatic, because I would like to keep things as
simple as possible.

Thank you very much for sharing your ideas Laurent!

**Comment by ChiefORZ** [comment]
I am experiencing the same bug.

But the update with the paper-dialog is awesome! thanks for it

**Comment by ojcarcete** [comment]
Just pushed an update featuring initial integration with third party themes by trying to auto select black or white text color.

At the very least it should work with both the default theme and Play Midnight.

**Comment by leTel** [comment]
Looks good with Play Midnight ! I'm impressed by your reactivity ! I'll update (once more) my comment on the Google Chrome webstore (my name is Laurent). Thank you very much and good day sir !
